# Generated by Django 2.2.5 on 2019-09-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_auto_20190923_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='poster',
            field=models.ImageField(blank=True, upload_to='poster/'),
        ),
    ]
